// Guess The Impostor question bank.
//
// Two things were wrong with the old bank:
//   1. impostorIndex was 3 in all 50 questions - the answer was ALWAYS the last
//      option. Options are shuffled at runtime now (see GuessImpostor.jsx), and
//      the indices below are varied too so a stale build can't leak the answer.
//   2. Every impostor was a joke (Toaster, KFC, Sandwich). Nothing to think
//      about. The medium and hard tiers below keep all four items inside tech,
//      so the player has to know the actual distinction.
//
// Each game draws 2 easy + 3 medium + 1 hard, so the difficulty is identical
// for every player in the queue.

export const GUESS_IMPOSTOR_QUESTIONS = [
  // --- easy: the impostor is obviously not a tech thing ---------------------
  {
    category: 'Social Media Apps',
    items: ['Facebook', 'Instagram', 'Microsoft Excel', 'Twitter'],
    impostorIndex: 2,
    reason: 'Excel is a spreadsheet app, the rest are social media.',
    difficulty: 'easy',
  },
  {
    category: 'Tech Companies',
    items: ['Google', "McDonald's", 'Apple', 'Microsoft'],
    impostorIndex: 1,
    reason: "McDonald's is a fast food chain, not a tech company.",
    difficulty: 'easy',
  },
  {
    category: 'Smartphone Brands',
    items: ['Toyota', 'Samsung', 'Apple', 'OnePlus'],
    impostorIndex: 0,
    reason: 'Toyota makes cars, not smartphones.',
    difficulty: 'easy',
  },
  {
    category: 'Programming Languages',
    items: ['Python', 'Java', 'C++', 'English'],
    impostorIndex: 3,
    reason: 'English is a spoken language, not a programming language.',
    difficulty: 'easy',
  },
  {
    category: 'Ride Sharing Apps',
    items: ['Uber', 'Tinder', 'Ola', 'Rapido'],
    impostorIndex: 1,
    reason: 'Tinder is a dating app.',
    difficulty: 'easy',
  },
  {
    category: 'Food Delivery Apps',
    items: ['Spotify', 'Zomato', 'Swiggy', 'Zepto'],
    impostorIndex: 0,
    reason: 'Spotify is for music streaming.',
    difficulty: 'easy',
  },
  {
    category: 'E-commerce Sites',
    items: ['Amazon', 'Flipkart', 'Myntra', 'WhatsApp'],
    impostorIndex: 3,
    reason: 'WhatsApp is a messaging app.',
    difficulty: 'easy',
  },
  {
    category: 'Messaging Apps',
    items: ['WhatsApp', 'Netflix', 'Telegram', 'Signal'],
    impostorIndex: 1,
    reason: 'Netflix is a video streaming service.',
    difficulty: 'easy',
  },
  {
    category: 'Cloud Storage',
    items: ['Google Drive', 'Dropbox', 'Bluetooth', 'OneDrive'],
    impostorIndex: 2,
    reason: 'Bluetooth is a wireless connection standard, not storage.',
    difficulty: 'easy',
  },
  {
    category: 'AI Tools',
    items: ['MS Paint', 'ChatGPT', 'Gemini', 'Midjourney'],
    impostorIndex: 0,
    reason: 'MS Paint is a basic drawing program with no AI in it.',
    difficulty: 'easy',
  },
  {
    category: 'Video Games',
    items: ['Minecraft', 'Fortnite', 'Chrome', 'Roblox'],
    impostorIndex: 2,
    reason: 'Chrome is a web browser.',
    difficulty: 'easy',
  },
  {
    category: 'Internet Domains',
    items: ['.com', '.org', '.exe', '.net'],
    impostorIndex: 2,
    reason: '.exe is a program file extension, not a domain ending.',
    difficulty: 'easy',
  },
  {
    category: 'Computer Parts',
    items: ['Motherboard', 'Graphics Card', 'Power Supply', 'Stapler'],
    impostorIndex: 3,
    reason: 'A stapler is stationery.',
    difficulty: 'easy',
  },
  {
    category: 'Wearable Tech',
    items: ['Apple Watch', 'Fitbit', 'Desktop PC', 'Galaxy Watch'],
    impostorIndex: 2,
    reason: 'A desktop PC is not something you wear.',
    difficulty: 'easy',
  },
  {
    category: 'Mobile Processors',
    items: ['Snapdragon', 'MediaTek', 'Exynos', 'Ceiling Fan'],
    impostorIndex: 3,
    reason: 'A ceiling fan is not a processor.',
    difficulty: 'easy',
  },

  // --- medium: everything is tech, one is a different KIND of tech ----------
  {
    category: 'Web Browsers',
    items: ['Chrome', 'Bing', 'Firefox', 'Safari'],
    impostorIndex: 1,
    reason: 'Bing is a search engine. You use it inside a browser.',
    difficulty: 'medium',
  },
  {
    category: 'Input Devices',
    items: ['Mouse', 'Keyboard', 'Projector', 'Scanner'],
    impostorIndex: 2,
    reason: 'A projector is an output device — it shows you information.',
    difficulty: 'medium',
  },
  {
    category: 'Output Devices',
    items: ['Monitor', 'Printer', 'Microphone', 'Speaker'],
    impostorIndex: 2,
    reason: 'A microphone takes input in, the others put output out.',
    difficulty: 'medium',
  },
  {
    category: 'Google Products',
    items: ['Gmail', 'Google Drive', 'Keynote', 'Google Maps'],
    impostorIndex: 2,
    reason: 'Keynote is a presentation app made by Apple.',
    difficulty: 'medium',
  },
  {
    category: 'Apple Products',
    items: ['iPad', 'MacBook', 'Surface Pro', 'AirPods'],
    impostorIndex: 2,
    reason: 'The Surface Pro is made by Microsoft.',
    difficulty: 'medium',
  },
  {
    category: 'Microsoft Products',
    items: ['Windows', 'Xbox', 'Azure', 'Chromebook'],
    impostorIndex: 3,
    reason: 'Chromebooks run ChromeOS, made by Google.',
    difficulty: 'medium',
  },
  {
    category: 'Owned by Meta',
    items: ['Instagram', 'WhatsApp', 'Twitter', 'Facebook'],
    impostorIndex: 2,
    reason: 'Twitter (now X) is not owned by Meta.',
    difficulty: 'medium',
  },
  {
    category: 'Mobile Operating Systems',
    items: ['Android', 'iOS', 'Windows 11', 'HarmonyOS'],
    impostorIndex: 2,
    reason: 'Windows 11 is a desktop and laptop operating system.',
    difficulty: 'medium',
  },
  {
    category: 'Storage Devices',
    items: ['SSD', 'Hard Disk', 'RAM', 'SD Card'],
    impostorIndex: 2,
    reason: 'RAM is temporary working memory — it empties when you power off.',
    difficulty: 'medium',
  },
  {
    category: 'Version Control',
    items: ['Git', 'SVN', 'Docker', 'Mercurial'],
    impostorIndex: 2,
    reason: 'Docker packages and runs applications, it does not track code history.',
    difficulty: 'medium',
  },
  {
    category: 'Code Editors',
    items: ['VS Code', 'Sublime Text', 'Notepad++', 'Postman'],
    impostorIndex: 3,
    reason: 'Postman is a tool for testing APIs, not for writing code.',
    difficulty: 'medium',
  },
  {
    category: 'Video Call Apps',
    items: ['Zoom', 'Google Meet', 'Trello', 'Microsoft Teams'],
    impostorIndex: 2,
    reason: 'Trello is a task and project board.',
    difficulty: 'medium',
  },
  {
    category: 'Cloud Platforms',
    items: ['AWS', 'Azure', 'GitHub', 'Google Cloud'],
    impostorIndex: 2,
    reason: 'GitHub hosts code repositories, it is not a cloud computing platform.',
    difficulty: 'medium',
  },
  {
    category: 'Linux Distributions',
    items: ['Ubuntu', 'Fedora', 'FreeBSD', 'Debian'],
    impostorIndex: 2,
    reason: 'FreeBSD is a BSD system, it does not use the Linux kernel.',
    difficulty: 'medium',
  },
  {
    category: 'Wireless Technologies',
    items: ['Bluetooth', 'Wi-Fi', 'Ethernet', 'NFC'],
    impostorIndex: 2,
    reason: 'Ethernet is a wired connection.',
    difficulty: 'medium',
  },
  {
    category: 'Web Technologies',
    items: ['HTML', 'CSS', 'JavaScript', 'MySQL'],
    impostorIndex: 3,
    reason: 'MySQL is a database that runs on the server, not in the browser.',
    difficulty: 'medium',
  },
  {
    category: 'Antivirus Software',
    items: ['Norton', 'Adobe Premiere', 'McAfee', 'Kaspersky'],
    impostorIndex: 1,
    reason: 'Adobe Premiere is video editing software.',
    difficulty: 'medium',
  },
  {
    category: 'Search Engines',
    items: ['Google', 'DuckDuckGo', 'Windows', 'Bing'],
    impostorIndex: 2,
    reason: 'Windows is an operating system.',
    difficulty: 'medium',
  },

  // --- hard: all four are tech, the difference is a real concept -----------
  {
    category: 'Programming Languages',
    items: ['Python', 'Ruby', 'HTML', 'Perl'],
    impostorIndex: 2,
    reason: 'HTML is a markup language — it describes structure, it cannot compute.',
    difficulty: 'hard',
  },
  {
    category: 'Frontend Frameworks',
    items: ['React', 'Angular', 'Django', 'Vue'],
    impostorIndex: 2,
    reason: 'Django is a backend framework, and it is Python not JavaScript.',
    difficulty: 'hard',
  },
  {
    category: 'NoSQL Databases',
    items: ['MongoDB', 'PostgreSQL', 'Cassandra', 'Redis'],
    impostorIndex: 1,
    reason: 'PostgreSQL is a relational SQL database.',
    difficulty: 'hard',
  },
  {
    category: 'AWS Services',
    items: ['S3', 'EC2', 'Firestore', 'Lambda'],
    impostorIndex: 2,
    reason: 'Firestore is a Google Cloud (Firebase) database.',
    difficulty: 'hard',
  },
  {
    category: 'CSS Frameworks',
    items: ['Tailwind', 'Bootstrap', 'jQuery', 'Bulma'],
    impostorIndex: 2,
    reason: 'jQuery is a JavaScript library, not a styling framework.',
    difficulty: 'hard',
  },
  {
    category: 'Package Managers',
    items: ['npm', 'pip', 'Jenkins', 'Maven'],
    impostorIndex: 2,
    reason: 'Jenkins is a CI server that runs builds, it does not install packages.',
    difficulty: 'hard',
  },
  {
    category: 'Compiled Languages',
    items: ['C', 'Go', 'JavaScript', 'Rust'],
    impostorIndex: 2,
    reason: 'JavaScript is interpreted at runtime rather than compiled ahead of time.',
    difficulty: 'hard',
  },
  {
    category: 'Sorting Algorithms',
    items: ['Merge Sort', 'Quick Sort', 'Binary Search', 'Bubble Sort'],
    impostorIndex: 2,
    reason: 'Binary Search finds an item, it does not sort anything.',
    difficulty: 'hard',
  },
  {
    category: 'OOP Concepts',
    items: ['Inheritance', 'Encapsulation', 'Recursion', 'Polymorphism'],
    impostorIndex: 2,
    reason: 'Recursion is a general technique, not one of the OOP pillars.',
    difficulty: 'hard',
  },
  {
    category: 'HTTP Methods',
    items: ['GET', 'POST', 'PUSH', 'DELETE'],
    impostorIndex: 2,
    reason: 'PUSH is not an HTTP method. You are thinking of PUT.',
    difficulty: 'hard',
  },
  {
    category: 'Data Structures',
    items: ['Stack', 'Queue', 'Quick Sort', 'Linked List'],
    impostorIndex: 2,
    reason: 'Quick Sort is an algorithm that runs on data structures.',
    difficulty: 'hard',
  },
  {
    category: 'Statically Typed Languages',
    items: ['Java', 'C++', 'Python', 'TypeScript'],
    impostorIndex: 2,
    reason: 'Python is dynamically typed — types are checked while it runs.',
    difficulty: 'hard',
  },
  {
    category: 'Google Cloud Services',
    items: ['BigQuery', 'Cloud Run', 'DynamoDB', 'Firestore'],
    impostorIndex: 2,
    reason: 'DynamoDB is Amazon\'s database.',
    difficulty: 'hard',
  },
  {
    category: 'Code Hosting Platforms',
    items: ['GitHub', 'GitLab', 'Docker Hub', 'Bitbucket'],
    impostorIndex: 2,
    reason: 'Docker Hub stores container images, not source code repositories.',
    difficulty: 'hard',
  },
  {
    category: 'JavaScript Runtimes',
    items: ['Node.js', 'Deno', 'Flask', 'Bun'],
    impostorIndex: 2,
    reason: 'Flask is a Python web framework.',
    difficulty: 'hard',
  },
  // --- easy (second batch) --------------------------------------------------
  {
    category: 'Operating Systems',
    items: ['Windows', 'Linux', 'macOS', 'Photoshop'],
    impostorIndex: 3,
    reason: 'Photoshop is an application that runs ON an operating system.',
    difficulty: 'easy',
  },
  {
    category: 'Music Streaming Apps',
    items: ['Spotify', 'JioSaavn', 'Gaana', 'Uber'],
    impostorIndex: 3,
    reason: 'Uber is a ride hailing app.',
    difficulty: 'easy',
  },
  {
    category: 'Video Streaming Services',
    items: ['Netflix', 'Hotstar', 'Prime Video', 'Paytm'],
    impostorIndex: 3,
    reason: 'Paytm is a payments app.',
    difficulty: 'easy',
  },
  {
    category: 'Payment Apps',
    items: ['Paytm', 'PhonePe', 'Google Pay', 'Zomato'],
    impostorIndex: 3,
    reason: 'Zomato is for ordering food.',
    difficulty: 'easy',
  },
  {
    category: 'Computer Input Devices',
    items: ['Keyboard', 'Mouse', 'Webcam', 'Printer'],
    impostorIndex: 3,
    reason: 'A printer produces output, it does not take input in.',
    difficulty: 'easy',
  },
  {
    category: 'Programming Languages',
    items: ['C++', 'Python', 'Ruby', 'Photoshop'],
    impostorIndex: 3,
    reason: 'Photoshop is image editing software.',
    difficulty: 'easy',
  },
  {
    category: 'Search & Browsers',
    items: ['Chrome', 'Firefox', 'Opera', 'Excel'],
    impostorIndex: 3,
    reason: 'Excel is a spreadsheet program.',
    difficulty: 'easy',
  },
  {
    category: 'Gaming Consoles',
    items: ['PlayStation', 'Xbox', 'Nintendo Switch', 'Chromecast'],
    impostorIndex: 3,
    reason: 'Chromecast streams video to a TV, it is not a games console.',
    difficulty: 'easy',
  },
  {
    category: 'Indian IT Companies',
    items: ['Infosys', 'TCS', 'Wipro', 'Adobe'],
    impostorIndex: 3,
    reason: 'Adobe is an American software company.',
    difficulty: 'easy',
  },
  {
    category: 'Laptop Brands',
    items: ['Dell', 'HP', 'Lenovo', 'Bosch'],
    impostorIndex: 3,
    reason: 'Bosch makes home appliances and car parts.',
    difficulty: 'easy',
  },
  {
    category: 'Chat Apps',
    items: ['Telegram', 'Discord', 'Slack', 'Photoshop'],
    impostorIndex: 3,
    reason: 'Photoshop is not a messaging app.',
    difficulty: 'easy',
  },
  {
    category: 'Units of Digital Storage',
    items: ['Kilobyte', 'Megabyte', 'Gigabyte', 'Kilometre'],
    impostorIndex: 3,
    reason: 'A kilometre measures distance, not data.',
    difficulty: 'easy',
  },
  {
    category: 'Parts Inside a Computer',
    items: ['RAM', 'CPU', 'Motherboard', 'Monitor'],
    impostorIndex: 3,
    reason: 'The monitor sits outside the cabinet - it is a peripheral.',
    difficulty: 'easy',
  },
  {
    category: 'Social Media Founders',
    items: ['Mark Zuckerberg', 'Jack Dorsey', 'Kevin Systrom', 'Ratan Tata'],
    impostorIndex: 3,
    reason: 'Ratan Tata led the Tata Group, not a social network.',
    difficulty: 'easy',
  },
  {
    category: 'Web Related Terms',
    items: ['Browser', 'Website', 'Hyperlink', 'Screwdriver'],
    impostorIndex: 3,
    reason: 'A screwdriver is a hand tool.',
    difficulty: 'easy',
  },

  // --- medium (second batch) ------------------------------------------------
  {
    category: 'Text Editors',
    items: ['Vim', 'Emacs', 'Nano', 'Bash'],
    impostorIndex: 3,
    reason: 'Bash is a command shell, not a text editor.',
    difficulty: 'medium',
  },
  {
    category: 'Compiled Output',
    items: ['.exe', '.out', '.class', '.txt'],
    impostorIndex: 3,
    reason: '.txt is plain text, not something produced by a compiler.',
    difficulty: 'medium',
  },
  {
    category: 'Loops and Control Flow',
    items: ['for', 'while', 'do-while', 'int'],
    impostorIndex: 3,
    reason: 'int declares a data type, it does not control flow.',
    difficulty: 'medium',
  },
  {
    category: 'C Data Types',
    items: ['int', 'float', 'char', 'return'],
    impostorIndex: 3,
    reason: 'return is a statement, not a data type.',
    difficulty: 'medium',
  },
  {
    category: 'HTML Tags',
    items: ['<div>', '<span>', '<p>', '<print>'],
    impostorIndex: 3,
    reason: 'There is no <print> tag in HTML.',
    difficulty: 'medium',
  },
  {
    category: 'Linear Data Structures',
    items: ['Array', 'Stack', 'Queue', 'Binary Tree'],
    impostorIndex: 3,
    reason: 'A binary tree is hierarchical, not linear.',
    difficulty: 'medium',
  },
  {
    category: 'Google Services',
    items: ['Google Maps', 'YouTube', 'Google Photos', 'OneDrive'],
    impostorIndex: 3,
    reason: 'OneDrive is Microsoft cloud storage.',
    difficulty: 'medium',
  },
  {
    category: 'Adobe Products',
    items: ['Photoshop', 'Illustrator', 'After Effects', 'Figma'],
    impostorIndex: 3,
    reason: 'Figma is made by an independent company. Adobe tried to buy it, but the deal was called off in 2023.',
    difficulty: 'medium',
  },
  {
    category: 'Python Keywords',
    items: ['def', 'lambda', 'yield', 'void'],
    impostorIndex: 3,
    reason: 'void is used in C and Java, not Python.',
    difficulty: 'medium',
  },
  {
    category: 'Network Devices',
    items: ['Router', 'Switch', 'Modem', 'Scanner'],
    impostorIndex: 3,
    reason: 'A scanner digitises documents, it does not move network traffic.',
    difficulty: 'medium',
  },
  {
    category: 'Image File Formats',
    items: ['.png', '.jpg', '.svg', '.mp3'],
    impostorIndex: 3,
    reason: '.mp3 is an audio format.',
    difficulty: 'medium',
  },
  {
    category: 'Types of Memory',
    items: ['RAM', 'ROM', 'Cache', 'GPU'],
    impostorIndex: 3,
    reason: 'A GPU is a processor, not a memory type.',
    difficulty: 'medium',
  },
  {
    category: 'Logic Gates',
    items: ['AND', 'OR', 'XOR', 'SUM'],
    impostorIndex: 3,
    reason: 'SUM is an operation, not a basic logic gate.',
    difficulty: 'medium',
  },
  {
    category: 'Git Commands',
    items: ['git commit', 'git push', 'git merge', 'git compile'],
    impostorIndex: 3,
    reason: 'There is no "git compile" command.',
    difficulty: 'medium',
  },
  {
    category: 'Number Systems',
    items: ['Binary', 'Octal', 'Hexadecimal', 'Numerical'],
    impostorIndex: 3,
    reason: '"Numerical" is not a number system.',
    difficulty: 'medium',
  },
  {
    category: 'Mobile App Stores',
    items: ['Play Store', 'App Store', 'Galaxy Store', 'Microsoft Word'],
    impostorIndex: 3,
    reason: 'Microsoft Word is a word processor.',
    difficulty: 'medium',
  },
  {
    category: 'Web Servers',
    items: ['Apache', 'Nginx', 'IIS', 'MySQL'],
    impostorIndex: 3,
    reason: 'MySQL is a database server, not a web server.',
    difficulty: 'medium',
  },
  {
    category: 'CSS Properties',
    items: ['margin', 'padding', 'border', 'function'],
    impostorIndex: 3,
    reason: 'function belongs to programming languages, not CSS.',
    difficulty: 'medium',
  },

  // --- hard (second batch) --------------------------------------------------
  {
    category: 'Interpreted Languages',
    items: ['Python', 'Ruby', 'PHP', 'C'],
    impostorIndex: 3,
    reason: 'C is compiled ahead of time, not interpreted.',
    difficulty: 'hard',
  },
  {
    category: 'Stable Sorting Algorithms',
    items: ['Merge Sort', 'Insertion Sort', 'Bubble Sort', 'Quick Sort'],
    impostorIndex: 3,
    reason: 'Quick Sort is not stable - equal elements can swap order.',
    difficulty: 'hard',
  },
  {
    category: 'O(n log n) Sorts',
    items: ['Merge Sort', 'Heap Sort', 'Quick Sort (average)', 'Bubble Sort'],
    impostorIndex: 3,
    reason: 'Bubble Sort is O(n squared).',
    difficulty: 'hard',
  },
  {
    category: 'NoSQL Database Types',
    items: ['Document store', 'Key-value store', 'Graph database', 'Relational table'],
    impostorIndex: 3,
    reason: 'A relational table is the SQL model NoSQL moves away from.',
    difficulty: 'hard',
  },
  {
    category: 'HTTP Status Families',
    items: ['2xx Success', '3xx Redirect', '4xx Client Error', '6xx Network Error'],
    impostorIndex: 3,
    reason: 'There is no 6xx family in HTTP.',
    difficulty: 'hard',
  },
  {
    category: 'OSI Model Layers',
    items: ['Transport', 'Network', 'Data Link', 'Compiler'],
    impostorIndex: 3,
    reason: 'Compiler is not a network layer.',
    difficulty: 'hard',
  },
  {
    category: 'Process Synchronisation',
    items: ['Semaphore', 'Mutex', 'Monitor', 'Compiler'],
    impostorIndex: 3,
    reason: 'A compiler translates code, it does not synchronise processes.',
    difficulty: 'hard',
  },
  {
    category: 'Containers & Orchestration',
    items: ['Docker', 'Kubernetes', 'Podman', 'Postman'],
    impostorIndex: 3,
    reason: 'Postman is an API testing tool.',
    difficulty: 'hard',
  },
  {
    category: 'Version Control Systems',
    items: ['Git', 'Mercurial', 'Subversion', 'Gradle'],
    impostorIndex: 3,
    reason: 'Gradle is a build tool.',
    difficulty: 'hard',
  },
  {
    category: 'Build Tools',
    items: ['Maven', 'Gradle', 'Make', 'Kubernetes'],
    impostorIndex: 3,
    reason: 'Kubernetes orchestrates containers, it does not build code.',
    difficulty: 'hard',
  },
  {
    category: 'Self-Balancing Trees',
    items: ['AVL Tree', 'Red-Black Tree', 'B-Tree', 'Binary Search Tree'],
    impostorIndex: 3,
    reason: 'A plain BST has no balancing rule and can degrade to a list.',
    difficulty: 'hard',
  },
  {
    category: 'Python Web Frameworks',
    items: ['Django', 'Flask', 'FastAPI', 'Express'],
    impostorIndex: 3,
    reason: 'Express is a Node.js framework.',
    difficulty: 'hard',
  },
  {
    category: 'Transport Layer Protocols',
    items: ['TCP', 'UDP', 'SCTP', 'HTTP'],
    impostorIndex: 3,
    reason: 'HTTP sits at the application layer, above transport.',
    difficulty: 'hard',
  },
  {
    category: 'ACID Properties',
    items: ['Atomicity', 'Consistency', 'Durability', 'Availability'],
    impostorIndex: 3,
    reason: 'Availability belongs to the CAP theorem, not ACID.',
    difficulty: 'hard',
  },
  {
    category: 'Testing Frameworks',
    items: ['JUnit', 'PyTest', 'Jest', 'Jenkins'],
    impostorIndex: 3,
    reason: 'Jenkins runs CI pipelines, it is not a test framework.',
    difficulty: 'hard',
  },
];
