// TECH-O-FIRE question bank.
//
// Audience is B.Tech FIRST YEAR, so the tiers are pitched at what they have
// actually met by semester 1-2:
//   easy    general tech literacy - phones, browsers, big tech, acronyms
//   medium  intro programming / CS fundamentals from first-year coursework
//   hard    stretch questions; only ONE per game so nobody is buried by them
//
// Each game draws 4 easy + 3 medium + 1 hard at random from these tiers, and
// the options are shuffled per question at runtime. The bank is deliberately
// far larger than a single game needs: at a stall, students watch each other
// play, and a shallow pool means the tenth person in the queue has already
// seen every question. Keep it that way - if you add questions, add them to
// the tier that needs depth rather than replacing what is here.
//
// correctIndex below is only the answer's position in this file. It is never
// the position a player sees, so it is fine that most of them are 0.

export const TECH_QUIZ_QUESTIONS = [
  // ===================== EASY =====================
  { question: 'What does HTML stand for?', options: ['Hyper Text Markup Language', 'High Text Machine Language', 'Hyper Tabular Markup Language', 'Home Tool Markup Language'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does CPU stand for?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Process Utility', 'Core Processing Unit'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does RAM stand for?', options: ['Random Access Memory', 'Rapid Access Memory', 'Readable Active Memory', 'Remote Access Module'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which company created the Android operating system?', options: ['Google', 'Apple', 'Samsung', 'Microsoft'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does "www" stand for in a website address?', options: ['World Wide Web', 'Web World Wide', 'Wide Web World', 'World Web Wide'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is a search engine?', options: ['Bing', 'Photoshop', 'Excel', 'Blender'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Who co-founded Microsoft alongside Bill Gates?', options: ['Paul Allen', 'Steve Jobs', 'Steve Ballmer', 'Larry Page'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does GPU stand for?', options: ['Graphics Processing Unit', 'General Processing Unit', 'Graphical Peripheral Unit', 'Game Processing Unit'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which company owns YouTube?', options: ['Google', 'Meta', 'Amazon', 'Netflix'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does URL stand for?', options: ['Uniform Resource Locator', 'Universal Resource Link', 'Uniform Reference Locator', 'United Resource Locator'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is an operating system?', options: ['Linux', 'Firefox', 'Oracle', 'Python'], correctIndex: 0, difficulty: 'easy' },
  { question: 'In computing, what is a "bug"?', options: ['An error or flaw in software', 'A type of virus', 'A hardware upgrade', 'A network cable'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does VPN stand for?', options: ['Virtual Private Network', 'Verified Public Network', 'Virtual Public Node', 'Variable Private Network'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which programming language shares its name with a type of coffee?', options: ['Java', 'Python', 'Ruby', 'Swift'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does the "G" in 5G stand for?', options: ['Generation', 'Gigabyte', 'Global', 'Gateway'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which company makes the iPhone?', options: ['Apple', 'Samsung', 'Xiaomi', 'Nokia'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does PDF stand for?', options: ['Portable Document Format', 'Printed Document File', 'Personal Data File', 'Public Document Format'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is NOT a web browser?', options: ['Photoshop', 'Chrome', 'Safari', 'Edge'], correctIndex: 0, difficulty: 'easy' },
  { question: "Who is often called the world's first computer programmer?", options: ['Ada Lovelace', 'Alan Turing', 'Grace Hopper', 'Charles Babbage'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does Wi-Fi primarily let a device do?', options: ['Connect to a network wirelessly', 'Increase storage space', 'Cool the processor', 'Charge the battery'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which short-video app was made by ByteDance?', options: ['TikTok', 'LinkedIn', 'Pinterest', 'Reddit'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does "AI" stand for?', options: ['Artificial Intelligence', 'Automated Interface', 'Advanced Integration', 'Applied Informatics'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does USB stand for?', options: ['Universal Serial Bus', 'United System Bus', 'Universal Storage Box', 'Unified Serial Board'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these keeps your data even after the computer is switched off?', options: ['Hard Disk', 'RAM', 'Cache', 'CPU Register'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Who founded Facebook?', options: ['Mark Zuckerberg', 'Jack Dorsey', 'Evan Spiegel', 'Kevin Systrom'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is an email service?', options: ['Gmail', 'Spotify', 'Figma', 'Canva'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does LED stand for?', options: ['Light Emitting Diode', 'Low Energy Display', 'Linear Electric Device', 'Light Enhanced Diode'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does SMS stand for?', options: ['Short Message Service', 'Simple Mail System', 'Secure Message Standard', 'Speedy Messaging Service'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which company develops Windows and Microsoft Office?', options: ['Microsoft', 'Apple', 'IBM', 'Adobe'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Who is the CEO of Tesla and SpaceX?', options: ['Elon Musk', 'Jeff Bezos', 'Tim Cook', 'Sundar Pichai'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is a video conferencing app?', options: ['Zoom', 'Photoshop', 'WinRAR', 'Notepad'], correctIndex: 0, difficulty: 'easy' },
  { question: 'The word "app" is short for what?', options: ['Application', 'Appliance', 'Approach', 'Apparatus'], correctIndex: 0, difficulty: 'easy' },
  { question: "What is Google's web browser called?", options: ['Chrome', 'Safari', 'Edge', 'Opera'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Bluetooth is mainly used for what?', options: ['Short-range wireless connections', 'Long-distance satellite links', 'Cooling the processor', 'Storing files permanently'], correctIndex: 0, difficulty: 'easy' },
  { question: 'In email, what is "spam"?', options: ['Unwanted junk mail', 'An encrypted attachment', 'A delivery receipt', 'A saved draft'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is a programming language?', options: ['Python', 'Microsoft Word', 'Windows', 'Google Drive'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does GPS stand for?', options: ['Global Positioning System', 'General Purpose Satellite', 'Global Path Service', 'Guided Positioning Sensor'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does ISP stand for?', options: ['Internet Service Provider', 'Internal System Protocol', 'Integrated Server Platform', 'Internet Security Program'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does HTTP stand for?', options: ['HyperText Transfer Protocol', 'High Transfer Text Protocol', 'Hyperlink Text Transmission Process', 'Host Transfer Text Protocol'], correctIndex: 0, difficulty: 'easy' },
  { question: "What is Google's AI chatbot called?", options: ['Gemini', 'Cortana', 'Alexa', 'Watson'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does "open source" software mean?', options: ['Its source code is freely available', 'It only runs on Linux', 'It has no user interface', 'It cannot be modified'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which keyboard shortcut copies the selected text?', options: ['Ctrl + C', 'Ctrl + V', 'Ctrl + X', 'Ctrl + Z'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which keyboard shortcut pastes the copied text?', options: ['Ctrl + V', 'Ctrl + C', 'Ctrl + P', 'Ctrl + S'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is a cloud storage service?', options: ['Google Drive', 'VLC Media Player', 'Paint', 'Calculator'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Who founded Amazon?', options: ['Jeff Bezos', 'Larry Ellison', 'Michael Dell', 'Bill Gates'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does it mean to "download" a file?', options: ['Copy it from the internet to your device', 'Send it from your device to the internet', 'Permanently delete it', 'Print it on paper'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is an Indian IT services company?', options: ['Infosys', 'Siemens', 'Samsung', 'Nestle'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does UPI stand for in Indian digital payments?', options: ['Unified Payments Interface', 'Universal Payment Identity', 'United Payment Infrastructure', 'Unique Payment Index'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What is a QR code mainly used for?', options: ['Storing information a camera can scan', 'Cooling a device', 'Boosting Wi-Fi range', 'Compressing video'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which operating system runs on the iPhone?', options: ['iOS', 'Android', 'Windows Phone', 'HarmonyOS'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does "hardware" refer to?', options: ['The physical parts of a computer', 'The programs installed on it', 'Data stored in the cloud', 'The internet connection'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does "software" refer to?', options: ['Programs and instructions a computer runs', 'The metal casing', 'The power supply', 'The monitor'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does PC stand for?', options: ['Personal Computer', 'Program Console', 'Processing Chip', 'Portable Console'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is larger?', options: ['1 Megabyte', '1 Kilobyte', '1 Byte', '1 Bit'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which company owns Instagram and WhatsApp?', options: ['Meta', 'Google', 'Twitter', 'Snap'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What is the main job of an operating system?', options: ['Manage the hardware and run programs', 'Design websites', 'Edit photographs', 'Send emails only'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which of these is a popular code hosting website?', options: ['GitHub', 'Netflix', 'Swiggy', 'Zomato'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does "Ctrl + Z" usually do?', options: ['Undo the last action', 'Save the file', 'Close the window', 'Select everything'], correctIndex: 0, difficulty: 'easy' },
  { question: 'Which device is used to point and click on a screen?', options: ['Mouse', 'Monitor', 'Speaker', 'Printer'], correctIndex: 0, difficulty: 'easy' },
  { question: 'What does a "server" do?', options: ['Provides data or services to other computers', 'Only plays video games', 'Cools the data centre', 'Prints documents'], correctIndex: 0, difficulty: 'easy' },

  // ===================== MEDIUM =====================
  { question: 'What does CSS stand for?', options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System', 'Coded Style Sheets'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which data structure works on LIFO (Last In, First Out)?', options: ['Stack', 'Queue', 'Linked List', 'Tree'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which data structure works on FIFO (First In, First Out)?', options: ['Queue', 'Stack', 'Graph', 'Heap'], correctIndex: 0, difficulty: 'medium' },
  { question: 'In most programming languages, what is the index of the first element of an array?', options: ['0', '1', '-1', 'It depends on the array size'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does SQL stand for?', options: ['Structured Query Language', 'Sequential Query Language', 'Standard Question Language', 'System Query Logic'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is the decimal value of the binary number 1010?', options: ['10', '8', '12', '20'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Who created the Git version control system?', options: ['Linus Torvalds', 'Dennis Ritchie', 'Guido van Rossum', 'James Gosling'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does IDE stand for in software development?', options: ['Integrated Development Environment', 'Internal Data Engine', 'Interactive Design Editor', 'Integrated Debugging Extension'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which company originally developed the Java programming language?', options: ['Sun Microsystems', 'Microsoft', 'IBM', 'Apple'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which JavaScript library for building user interfaces was created at Facebook?', options: ['React', 'Angular', 'Vue', 'Svelte'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does API stand for?', options: ['Application Programming Interface', 'Applied Program Instruction', 'Automated Process Integration', 'Application Process Identifier'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does JSON stand for?', options: ['JavaScript Object Notation', 'Java Standard Output Name', 'JavaScript Ordered Nodes', 'Joined Simple Object Notation'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which command downloads a copy of a remote Git repository to your machine?', options: ['git clone', 'git push', 'git branch', 'git commit'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is the largest value an 8-bit unsigned integer can hold?', options: ['255', '256', '128', '512'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which company acquired GitHub in 2018?', options: ['Microsoft', 'Google', 'Amazon', 'Oracle'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which of these languages is NOT object-oriented?', options: ['C', 'C++', 'Java', 'Python'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does DOM stand for in web development?', options: ['Document Object Model', 'Data Object Mapping', 'Domain Oriented Markup', 'Dynamic Output Method'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which language is mainly used for building native iOS apps today?', options: ['Swift', 'Kotlin', 'Dart', 'Go'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which cross-platform app framework was created by Google?', options: ['Flutter', 'React Native', 'Ionic', 'Xamarin'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is the main job of a firewall?', options: ['Monitor and control network traffic', 'Speed up the processor', 'Back up files automatically', 'Compress large images'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which of these is a NoSQL database?', options: ['MongoDB', 'PostgreSQL', 'MySQL', 'SQLite'], correctIndex: 0, difficulty: 'medium' },
  { question: "What does an operating system's kernel do?", options: ['Manages hardware and core system resources', 'Renders the desktop wallpaper', 'Stores user documents', 'Compiles source code'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is the decimal value of the binary number 1111?', options: ['15', '16', '14', '31'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does a compiler do?', options: ['Translates source code into machine code', 'Runs the program line by line forever', 'Designs the user interface', 'Stores data in a database'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which loop is guaranteed to run at least once?', options: ['do-while loop', 'while loop', 'for loop', 'nested for loop'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is an algorithm?', options: ['A step-by-step procedure to solve a problem', 'A type of computer hardware', 'A programming language', 'A kind of database'], correctIndex: 0, difficulty: 'medium' },
  { question: 'The printf() function is most associated with which language?', options: ['C', 'Python', 'Java', 'HTML'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which symbol starts a single-line comment in C++ and Java?', options: ['//', '#', '<!--', '--'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which symbol starts a single-line comment in Python?', options: ['#', '//', '/*', '%'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is a variable in programming?', options: ['A named location that stores a value', 'A fixed number that never changes', 'A type of loop', 'An error message'], correctIndex: 0, difficulty: 'medium' },
  { question: 'RAM is best described as what kind of memory?', options: ['Volatile - it clears when power is lost', 'Permanent storage', 'Read-only memory', 'Cloud memory'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is the ASCII value of the character "A"?', options: ['65', '97', '48', '64'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which data structure is used in Breadth First Search (BFS)?', options: ['Queue', 'Stack', 'Heap', 'Trie'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which data structure is used in Depth First Search (DFS)?', options: ['Stack', 'Queue', 'Array', 'Hash Table'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is recursion?', options: ['A function calling itself', 'A loop that never ends', 'A type of variable', 'A sorting algorithm'], correctIndex: 0, difficulty: 'medium' },
  { question: 'How many values can a boolean hold?', options: ['2', '1', '4', 'Unlimited'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does IP stand for in "IP address"?', options: ['Internet Protocol', 'Internal Process', 'Information Packet', 'Integrated Port'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which of these is a relational database?', options: ['MySQL', 'MongoDB', 'Redis', 'Cassandra'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which HTML tag creates the largest heading?', options: ['<h1>', '<h6>', '<head>', '<big>'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which CSS property changes the colour of text?', options: ['color', 'background', 'font-family', 'text-align'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is debugging?', options: ['Finding and fixing errors in code', 'Writing documentation', 'Deleting old files', 'Designing a database'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does an interpreter do differently from a compiler?', options: ['It executes code line by line', 'It always runs faster', 'It only works with HTML', 'It removes all bugs'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is the binary representation of the decimal number 8?', options: ['1000', '1100', '0111', '1010'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which logic gate outputs 1 only when both inputs are 1?', options: ['AND', 'OR', 'NOT', 'XOR'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does a NOT gate do?', options: ['Inverts its input', 'Adds two inputs', 'Stores a bit', 'Multiplies inputs'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is pseudocode?', options: ['A plain-language outline of an algorithm', 'A language only compilers understand', 'Encrypted source code', 'A type of malware'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which of these is a linear data structure?', options: ['Array', 'Tree', 'Graph', 'Heap'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is the time complexity of linear search on an unsorted array?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(n squared)'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which keyword defines a function in Python?', options: ['def', 'func', 'function', 'define'], correctIndex: 0, difficulty: 'medium' },
  { question: 'In Python, what does the list index -1 refer to?', options: ['The last element', 'The first element', 'An error', 'The list length'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is an IP address used for?', options: ['Identifying a device on a network', 'Storing passwords', 'Measuring internet speed', 'Encrypting files'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which language runs directly inside a web browser?', options: ['JavaScript', 'C++', 'Java', 'Python'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is a syntax error?', options: ['Code that breaks the language grammar rules', 'A wrong answer produced at runtime', 'A slow algorithm', 'A missing file'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which of these is a markup language, not a programming language?', options: ['HTML', 'Python', 'C', 'Java'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does a primary key do in a database table?', options: ['Uniquely identifies each row', 'Sorts the table alphabetically', 'Encrypts the table', 'Stores the largest value'], correctIndex: 0, difficulty: 'medium' },
  { question: 'How many bits are there in one byte?', options: ['8', '4', '16', '32'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What does OOP stand for?', options: ['Object Oriented Programming', 'Open Output Protocol', 'Optimised Operation Process', 'Ordered Object Pattern'], correctIndex: 0, difficulty: 'medium' },
  { question: 'In OOP, what is a class?', options: ['A blueprint for creating objects', 'A single running object', 'A type of loop', 'A database table'], correctIndex: 0, difficulty: 'medium' },
  { question: 'What is the main purpose of a constructor in OOP?', options: ['Initialise a new object', 'Delete an object', 'Sort a list', 'Open a file'], correctIndex: 0, difficulty: 'medium' },
  { question: 'Which of these is NOT a valid variable name in most languages?', options: ['2ndValue', 'value2', '_value', 'valueTwo'], correctIndex: 0, difficulty: 'medium' },

  // ===================== HARD =====================
  { question: 'What is the time complexity of binary search on a sorted array?', options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(1)'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which port does HTTPS use by default?', options: ['443', '80', '22', '8080'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which port does SSH use by default?', options: ['22', '21', '443', '3306'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which design pattern restricts a class to a single instance?', options: ['Singleton', 'Factory', 'Observer', 'Adapter'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the main purpose of a Docker container?', options: ['Package an app with its dependencies so it runs anywhere', 'Encrypt network traffic', 'Speed up database queries', 'Replace the operating system kernel'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What does JWT stand for?', options: ['JSON Web Token', 'Java Web Toolkit', 'JavaScript Web Transfer', 'Joined Web Ticket'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which AWS service provides scalable object storage?', options: ['S3', 'EC2', 'Lambda', 'Route 53'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is Redux primarily used for in a React application?', options: ['State management', 'Routing between pages', 'Styling components', 'Running unit tests'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which HTTP method is normally used to create a new resource?', options: ['POST', 'GET', 'DELETE', 'HEAD'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which company created the Kotlin programming language?', options: ['JetBrains', 'Google', 'Oracle', 'Microsoft'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which of these is a CSS preprocessor?', options: ['SASS', 'Babel', 'Webpack', 'ESLint'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What does SaaS stand for?', options: ['Software as a Service', 'Storage as a Service', 'System as a Service', 'Security as a Service'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the average time complexity of quicksort?', options: ['O(n log n)', 'O(n)', 'O(n squared)', 'O(log n)'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What does the HTTP status code 404 mean?', options: ['Not Found', 'Server Error', 'Unauthorized', 'Request Timeout'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which protocol translates domain names into IP addresses?', options: ['DNS', 'DHCP', 'FTP', 'SMTP'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the worst-case time complexity of quicksort?', options: ['O(n squared)', 'O(n log n)', 'O(n)', 'O(log n)'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the average time complexity of a hash table lookup?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the time complexity of bubble sort in the worst case?', options: ['O(n squared)', 'O(n log n)', 'O(n)', 'O(1)'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the key difference between TCP and UDP?', options: ['TCP is connection-oriented and reliable', 'UDP guarantees delivery order', 'TCP is always faster', 'UDP encrypts all data'], correctIndex: 0, difficulty: 'hard' },
  { question: 'In databases, what does ACID stand for?', options: ['Atomicity, Consistency, Isolation, Durability', 'Access, Control, Integrity, Data', 'Atomic, Cached, Indexed, Distributed', 'Array, Class, Interface, Data'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the purpose of database normalization?', options: ['Reduce data redundancy', 'Increase storage usage', 'Encrypt sensitive columns', 'Speed up every possible query'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is a deadlock in operating systems?', options: ['Processes waiting on each other forever', 'A crashed application', 'A full hard disk', 'An infinite loop in one thread'], correctIndex: 0, difficulty: 'hard' },
  { question: 'At which OSI layer does HTTP operate?', options: ['Application layer', 'Transport layer', 'Network layer', 'Data Link layer'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What does CI/CD stand for?', options: ['Continuous Integration / Continuous Deployment', 'Code Inspection / Code Delivery', 'Central Index / Central Database', 'Compiled Interface / Compiled Driver'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which tree traversal of a Binary Search Tree gives values in sorted order?', options: ['Inorder', 'Preorder', 'Postorder', 'Level order'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is memoization?', options: ['Caching results of expensive function calls', 'Deleting unused memory', 'Sorting data in place', 'Encrypting stored values'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which HTTP status code means "Unauthorized"?', options: ['401', '403', '404', '500'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the height of a balanced binary search tree with n nodes?', options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(1)'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which of these sorting algorithms is stable?', options: ['Merge Sort', 'Quick Sort', 'Heap Sort', 'Selection Sort'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is cache memory?', options: ['Small fast memory close to the CPU', 'Long-term backup storage', 'A type of network buffer', 'Memory shared over the internet'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is a REST API expected to be?', options: ['Stateless between requests', 'Always written in Java', 'Connected by WebSockets', 'Limited to XML responses'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is a semaphore used for?', options: ['Process synchronisation', 'Image compression', 'Rendering graphics', 'Parsing HTML'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the purpose of virtual memory?', options: ['Let programs use more memory than physically installed', 'Speed up the GPU', 'Encrypt the hard disk', 'Back up files to the cloud'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which Git command combines another branch into your current one?', options: ['git merge', 'git clone', 'git status', 'git init'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which compiler phase checks whether the code follows the language grammar?', options: ['Syntax analysis', 'Lexical analysis', 'Code generation', 'Optimisation'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which HTTP method is idempotent?', options: ['GET', 'POST', 'PATCH', 'CONNECT'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What does a load balancer do?', options: ['Distributes traffic across multiple servers', 'Compresses images', 'Encrypts passwords', 'Indexes a database'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is the space complexity of merge sort?', options: ['O(n)', 'O(1)', 'O(log n)', 'O(n squared)'], correctIndex: 0, difficulty: 'hard' },
  { question: 'What is polymorphism in OOP?', options: ['One interface behaving differently for different types', 'Hiding internal data', 'Reusing code from a parent class', 'Creating one instance only'], correctIndex: 0, difficulty: 'hard' },
  { question: 'Which port does MySQL use by default?', options: ['3306', '5432', '27017', '6379'], correctIndex: 0, difficulty: 'hard' },
];
